### PR TITLE
Adding nested group support for non-AD servers

### PR DESCRIPTION
**Pull request by PhoenixIra**
## Proposed changes

This PR adds the feature mentioned in issue #10 for nested groups. By enabling the nested group feature in the settings, the plugin searches for group memberships of groups as well and includes them in the list of groups for a user.

~~Because of issue #12, I didn't tested the GUI yet.~~

### Your checklist for this pull request

- [x] PR is well described and the description can be used as commit message on squash
- [x] Related issues linked to PR if existing and labels set
- [x] Target branch is not master (in most cases develop should bet the target of choice) 
- [x] Code does not conflict with target branch
- [x] New code is covered with unit tests
- [ ] [Changelog entry file](https://github.com/scm-manager/changelog#changelog-entry-files) created in `gradle/changelog`
- [ ] Definition of Done's fulfilled: [DoD](https://github.com/scm-manager/scm-manager/blob/develop/docs/en/development/definition-of-done.md) // [UI DoD](https://github.com/scm-manager/scm-manager/blob/develop/docs/en/development/ui-dod.md)
- [ ] Documentation updated (only necessary for new features or changed behaviour)

### Checklist for branch merge request (not required for forks)

- [ ] Branch is green/blue on [Jenkins](https://oss.cloudogu.com/jenkins/)
- [ ] Quality Gate passed on [SonarQube](https://sonarcloud.io/organizations/scm-manager/projects)

### CODE REVIEW

**Comment by PhoenixIra** [comment]
By the way, I did not include javadoc, because the classes didn't had javadoc in the first place. I am, however, willing to add javadoc if requested.

**Comment by sdorra** [comment]
Thank you very much.

**Comment by sdorra** [comment]
The feature will be available with the version 2.1.0, which will be published today.

**Comment by PhoenixIra** [comment]
Great! 

By the way, I just noticed a dead code fragment in this merge, which slipped throw because I did not used a TS ide (sorry). Its in src/main/js/LdapConfigurationForm.tsx line 42, `searchFilterGroupByName: string;`. This string is never used. If you could remove it, that would be great.

**Comment by sdorra** [comment]
No problem.

**Comment by sdorra** [comment]
2.1.0 should be available now.

**Pull request merged**
